### ISSUE TITLE
error 'not url-safe' on url-safe characters

### ISSUE THREAD

**Issue by juliuste** [public-transport/validate-fptf#2]
In `id`s: Even on url-safe characters like `_`, I get an error. This is because `slugg` replaces every other char by `-`, I think.

**Comment by derhuerst** [comment]
Using [`strict-uri-encode`](https://npmjs.com/package/strict-uri-encode) should fix this.

Side note: Even though [this StackOverflow response mentions `.`](https://stackoverflow.com/questions/695438/safe-characters-for-friendly-url), I think `.` should not be allowed for e.g. filesystem safety. One might even go as far as saying only base58 is safe, but I understand this is cumbersome in some languages.
